{
  "sksl": {
    "entrypoint": "cloudy_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform float uTime;\nuniform vec2 uResolution;\nuniform vec3 uColor1;\nuniform vec3 uColor2;\n\nvec4 fragColor;\n\nfloat FLT_flutter_local_hash(inout vec2 p)\n{\n    p = fract(p * vec2(123.339996337890625, 345.45001220703125));\n    p += vec2(dot(p, p + vec2(34.345001220703125)));\n    return fract(p.x * p.y);\n}\n\nfloat FLT_flutter_local_noise(vec2 p)\n{\n    vec2 i = floor(p);\n    vec2 f = fract(p);\n    vec2 param = i;\n    float _56 = FLT_flutter_local_hash(param);\n    float a = _56;\n    vec2 param_1 = i + vec2(1.0, 0.0);\n    float _64 = FLT_flutter_local_hash(param_1);\n    float b = _64;\n    vec2 param_2 = i + vec2(0.0, 1.0);\n    float _70 = FLT_flutter_local_hash(param_2);\n    float c = _70;\n    vec2 param_3 = i + vec2(1.0);\n    float _76 = FLT_flutter_local_hash(param_3);\n    float d = _76;\n    vec2 u = (f * f) * (vec2(3.0) - (f * 2.0));\n    return mix(mix(a, b, u.x), mix(c, d, u.x), u.y);\n}\n\nfloat FLT_flutter_local_fbm(vec2 p)\n{\n    float value = 0.0;\n    float amplitude = 0.5;\n    float frequency = 1.0;\n    for (int i = 0; i < 5; i++)\n    {\n        vec2 param = p * frequency;\n        value += (FLT_flutter_local_noise(param) * amplitude);\n        frequency *= 2.0;\n        amplitude *= 0.5;\n    }\n    return value;\n}\n\nvoid FLT_main()\n{\n    vec2 uv = flutter_FragCoord.xy / uResolution;\n    uv *= 2.0;\n    vec2 motion = vec2(uTime * 0.02999999932944774627685546875, uTime * 0.0500000007450580596923828125);\n    vec2 param_1 = uv + motion;\n    float n = FLT_flutter_local_fbm(param_1);\n    vec3 color = mix(uColor1, uColor2, vec3(smoothstep(0.300000011920928955078125, 0.699999988079071044921875, n)));\n    fragColor = vec4((color * n) * 1.2000000476837158203125, 1.0);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uResolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uColor1",
        "rows": 3,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "uColor2",
        "rows": 3,
        "type": 10
      }
    ]
  }
}